### ISSUE TITLE
Adapter is crashing

### ISSUE THREAD

**Issue by mctom** [iobroker-community-adapters/ioBroker.spotify-premium#118]
The adapter keeps crashing. No action is performed in the adapter via ioBroker at this moment.

<html>
<body>

host.ioBroker | 2022-01-23 16:00:56.084 | error | instance system.adapter.spotify-premium.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
spotify-premium.0 | 2022-01-23 16:00:55.536 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
spotify-premium.0 | 2022-01-23 16:00:55.471 | error | Cannot read property 'common' of null
spotify-premium.0 | 2022-01-23 16:00:55.471 | error | TypeError: Cannot read property 'common' of null at copyObjectStates (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:483:59) at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:707:37 at processTicksAndRejections (internal/process/task_queues.js:95:5)
spotify-premium.0 | 2022-01-23 16:00:55.470 | error | unhandled promise rejection: Cannot read property 'common' of null
spotify-premium.0 | 2022-01-23 16:00:55.470 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
host.ioBroker | 2022-01-23 16:00:03.942 | error | instance system.adapter.spotify-premium.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

</body>
</html>

**Versions:**  
 - Adapter version: 1.1.9
 - JS-Controller version: 3.3.22
 - Node version: 14.18.2
 - Operating system: Linux Debian

**Comment by tetzlav** [comment]
+1
my adapter crashes with same logs under similar circumstances (versions, debian, ...)

**Comment by Apollon77** [comment]
Try GitHub verison
