### ISSUE TITLE
playlist error 504 / Unhandled promise rejection

### ISSUE THREAD

**Issue by Zaetti** [iobroker-community-adapters/ioBroker.spotify-premium#153]
Since Update 1.2.1 my spotify-premium adapter keeps restarting with the error shown in the loogfiles down below. On the same day i updated js and node.
I already deleted the instance and re-added it - no success.
I then tried to remove all special characters like äöü oder unerlines etc., re-added again with no success.

`host.raspberrypi
2022-09-04 09:49:52.526	error	instance system.adapter.spotify-premium.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.raspberrypi
2022-09-04 09:49:52.526	error	Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
host.raspberrypi
2022-09-04 09:49:52.526	error	Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:925:52
host.raspberrypi
2022-09-04 09:49:52.526	error	Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'trackIds')
host.raspberrypi
2022-09-04 09:49:52.525	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

spotify-premium.0
2022-09-04 09:49:51.854	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

spotify-premium.0
2022-09-04 09:49:51.852	info	terminating

spotify-premium.0
2022-09-04 09:49:51.782	error	Cannot read properties of undefined (reading 'trackIds')

spotify-premium.0
2022-09-04 09:49:51.781	error	TypeError: Cannot read properties of undefined (reading 'trackIds') at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:925:52 at processTicksAndRejections (node:internal/process/task_queues:96:5)

spotify-premium.0
2022-09-04 09:49:51.780	error	unhandled promise rejection: Cannot read properties of undefined (reading 'trackIds')

spotify-premium.0
2022-09-04 09:49:51.780	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

spotify-premium.0
2022-09-04 09:49:51.777	warn	error on load tracks(getPlaylistTracks): 504 owner: zät id: 4PXQ3juDvehA6KFeh71blF

spotify-premium.0
2022-09-04 09:49:51.777	warn	Error: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:360:38 at processTicksAndRejections (node:internal/process/task_queues:96:5)

spotify-premium.0
2022-09-04 09:49:51.776	warn	Error: at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:248:21) at getPlaylistTracks (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1047:12) at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:917:25

spotify-premium.0
2022-09-04 09:49:51.775	warn	http request error not handled, please debug

spotify-premium.0
2022-09-04 09:49:49.978	error	playlist error 504

spotify-premium.0
2022-09-04 09:49:49.977	warn	Error: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:360:38 at processTicksAndRejections (node:internal/process/task_queues:96:5)

spotify-premium.0
2022-09-04 09:49:49.976	warn	Error: at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:248:21) at getUsersPlaylist (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1004:16) at reloadUsersPlaylist (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:824:12) at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:196:21 at processTicksAndRejections (node:internal/process/task_queues:96:5)

spotify-premium.0
2022-09-04 09:49:49.974	warn	http request error not handled, please debug`

**Versions:**  
 - Adapter version: 1.2.1
 - JS-Controller version: 4.0.23
 - Node version: 16.15.1
 - Operating system: Debian

**Additional context**  
I also tried to set the playlist refresh intervall to 0 without success.
Is there any chance for me to debug the http request? Loglevel is on debug but there is not that much information.

A few days ago the adapter juzst threw the playlist error. Now it is crashing immediatly with unhandled promise exception.

Maybe i can send you my client id and secret if u want to test it out?

EDIT: I just tried the adapter version 1.2.1 on an old  Windows-iobroker instance (js 2.1.1 / node v10.17.0)  with exactly the same errors.
`<html>
<body>

  |   |   |  
-- | -- | -- | --
spotify-premium.0 | 2022-09-04 10:06:21.532 | warn | (22316) error on load tracks(getPlaylistTracks): 504 owner: zät id: 4PXQ3juDvehA6KFeh71blF
spotify-premium.0 | 2022-09-04 10:06:21.532 | warn | (22316) Error at request.then.response (C:\Program Files\iobroker\iOBrokerZWindows\node_modules\iobroker.spotify-premium\main.js:360:38) at process._tickCallback (internal/process/next_tick.js
spotify-premium.0 | 2022-09-04 10:06:21.532 | warn | (22316) Error at sendRequest (C:\Program Files\iobroker\iOBrokerZWindows\node_modules\iobroker.spotify-premium\main.js:248:21) at getPlaylistTracks (C:\Program Files\iobroker\iOBrokerZWindows\
spotify-premium.0 | 2022-09-04 10:06:21.532 | warn | (22316) http request error not handled, please debug

</body>
</html>`

Thank you
Zaetti

**Comment by Zaetti** [comment]
Any news on this one? :)

**Comment by xmace** [comment]
same issue here

**Comment by kekzmobile** [comment]
same here

**Comment by Zaetti** [comment]
sorry for asking again 🙈 any news ? :)

**Comment by petterpet** [comment]
I also have problems with restart loops after api errors:

```
2022-10-23 13:11:33.660 - warn: spotify-premium.0 (401130) unexpected api response http 503; continue polling
2022-10-23 13:11:33.727 - info: spotify-premium.0 (401130) State value to set for "spotify-premium.0.player.playlist.tracksTotal" has to be type "string" but received type "number"
2022-10-23 13:11:44.149 - info: spotify-premium.0 (401130) State value to set for "spotify-premium.0.player.playlist.tracksTotal" has to be type "string" but received type "number"
2022-10-23 13:12:31.801 - info: chromecast.0 (559825) NestHub - Playing - spotify:track:2XNaKS5wO5rPdgpPYVKria
2022-10-23 13:12:31.974 - warn: spotify-premium.0 (401130) State "spotify-premium.0.playlists.spotify-37i9dQZF1EQpj7X7UK8OOF.trackList" has no existing object, this might lead to an error in future versions
2022-10-23 13:16:24.635 - info: chromecast.0 (559825) NestHub - Playing - spotify:track:3ovjw5HZZv43SxTwApooCM
2022-10-23 13:16:24.959 - warn: spotify-premium.0 (401130) State "spotify-premium.0.playlists.spotify-37i9dQZF1EQpj7X7UK8OOF.trackList" has no existing object, this might lead to an error in future versions
2022-10-23 13:18:39.667 - error: spotify-premium.0 (401130) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-10-23 13:18:39.668 - error: spotify-premium.0 (401130) unhandled promise rejection: undefined
2022-10-23 13:18:39.668 - error: spotify-premium.0 (401130) undefined
2022-10-23 13:18:39.675 - info: spotify-premium.0 (401130) terminating
2022-10-23 13:18:39.675 - warn: spotify-premium.0 (401130) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-10-23 13:18:39.836 - warn: spotify-premium.0 (401130) error on load tracks(getPlaylistTracks): 503 owner: spotify id: 37i9dQZF1DWX7rdRjOECPW
2022-10-23 13:18:40.227 - error: host.iobroker Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'stateString')
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[1]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), :3:12)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[1]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:937:32
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[1]: at runMicrotasks ()
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'listNumber')
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[2]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), :3:12)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[2]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[2]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[2]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:958:21
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[2]: at runMicrotasks ()
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[2]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[3]: TypeError: Cannot read properties of undefined (reading 'listString')
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[3]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), :3:12)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[3]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[3]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[3]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:961:21
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[3]: at runMicrotasks ()
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[3]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[4]: TypeError: Cannot read properties of undefined (reading 'stateString')
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[4]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), :3:12)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[4]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[4]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[4]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:964:21
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[4]: at runMicrotasks ()
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[4]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[5]: TypeError: Cannot read properties of undefined (reading 'trackIdMap')
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[5]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), :3:12)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[5]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[5]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[5]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:967:21
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[5]: at runMicrotasks ()
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[5]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[6]: TypeError: Cannot read properties of undefined (reading 'trackIds')
2022-10-23 13:18:40.228 - error: host.iobroker Caught by controller[6]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), :3:12)
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[6]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[6]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[6]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:970:21
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[6]: at runMicrotasks ()
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[6]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[7]: TypeError: Cannot read properties of undefined (reading 'songs')
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[7]: at eval (eval at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:372:19), :3:12)
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[7]: at loadOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:373:13)
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[7]: at createOrDefault (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:387:13)
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[7]: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:973:21
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[7]: at runMicrotasks ()
2022-10-23 13:18:40.229 - error: host.iobroker Caught by controller[7]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-23 13:18:40.229 - error: host.iobroker instance system.adapter.spotify-premium.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-10-23 13:18:40.229 - info: host.iobroker Restart adapter system.adapter.spotify-premium.0 because enabled```

**Comment by Martin-int01** [comment]
same issue here

**Comment by cavernerg** [comment]
Reproducable for me by playing playlist "Christmas Hits" (The biggest Christmas songs of all time)  (and... yeah I know... :D ). 

`<html><body>


spotify-premium.0 | 2022-12-04 18:02:04.818 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
spotify-premium.0 | 2022-12-04 18:02:04.817 | info | terminating
spotify-premium.0 | 2022-12-04 18:02:04.722 | error | undefined
spotify-premium.0 | 2022-12-04 18:02:04.722 | error | unhandled promise rejection: undefined
spotify-premium.0 | 2022-12-04 18:02:04.721 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
spotify-premium.0 | 2022-12-04 18:02:03.530 | info | starting. Version 1.2.2 in /opt/iobroker/node_modules/iobroker.spotify-premium, node: v16.17.0, js-controller: 4.0.23
spotify-premium.0 | 2022-12-04 18:02:00.458 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
spotify-premium.0 | 2022-12-04 18:02:00.457 | info | terminating
spotify-premium.0 | 2022-12-04 18:02:00.368 | error | undefined
spotify-premium.0 | 2022-12-04 18:02:00.368 | error | unhandled promise rejection: undefined
spotify-premium.0 | 2022-12-04 18:02:00.368 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().


</body>
</html>`

Sadly, the adapter is not very communicative in terms of debugging.. :)

**Comment by Zaetti** [comment]
Anybody found a temporary solution for this till now?
`<html>
<body>


spotify-premium.0 | 2023-01-22 09:37:37.086 | error | playlist error 504
-- | -- | -- | --
spotify-premium.0 | 2023-01-22 09:37:37.086 | warn | Error: at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:360:38 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5)
spotify-premium.0 | 2023-01-22 09:37:37.085 | warn | Error: at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:248:21) at getUsersPlaylist (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1004:16) at reloadUsersPlaylist (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:824:12) at Timeout.pollPlaylistApi [as _onTimeout] (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1650:5) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
spotify-premium.0 | 2023-01-22 09:37:37.085 | warn | http request error not handled, please debug


</body>
</html>`

**Comment by Zaetti** [comment]
Any news on this one? Adapter became unusable 😔

**Comment by cavernerg** [comment]
I changed to calling the official Spotify app. Adapter crashes way to often

**Comment by aruttkamp** [comment]
Moin ! 
Ist dieses Problem noch aktuell ? 
Ich würde mich gerne darum kümmern, aber ich kann es aktuell nicht nachvollziehen.

**Comment by cavernerg** [comment]
Guten Morgen, 

Ich habe wegen des Fehlers den Adapter deaktiviert und springe in der vis in die Spotify App ab. Ich könnte in 3 Wochen nach dem Urlaub nochmal schauen, ob das Problem noch besteht

**Comment by aruttkamp** [comment]
> Guten Morgen,
> 
> Ich habe wegen des Fehlers den Adapter deaktiviert und springe in der vis in die Spotify App ab. Ich könnte in 3 Wochen nach dem Urlaub nochmal schauen, ob das Problem noch besteht

Vielen Dank für Dein Feedback. Dann gehe ich davon aus , dass das Problem noch besteht. 
Ich versuche mal das nachzuvollziehen ( und zu beheben ) .

**Comment by aruttkamp** [comment]
Ich kann dies nicht nachvollziehen. Wie genau kann ich es reproduzieren ?

**Comment by cavernerg** [comment]
Ich habe den Adapter Mal reaktiviert. Früher wurde es in Zusammenhang mit nicht mehr existierenden Playlisten und Songs gebracht in der Bibliothek, zu denen dann keine Infos mehr abgerufen werden konnten.
