### ISSUE TITLE
Warnings during Refresh interval for playlist information

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.spotify-premium#82]
Hello everybody,
I recently updated my ioBroker installation to Node 12 and js-controller 3.0.20.
After this update, I installed the Spotify Premium Adapter for the first time. Unfortunately I can not say whether the problems also occur with an older version of Node or js-controller.

At the moment I am using js-controller 3.1.4 and I have the same warnings in the logfile

When I start ioBroker via "iobroker start", I get the warnings below in the log file. Every 15 minutes (Refresh interval for playlist information.) the same warnings are logged

```
spotify-premium.0 | 2020-05-12 21:41:12.305 | warn | (14936) error on load tracks: 504
-- | -- | -- | --
spotify-premium.0 | 2020-05-12 21:41:12.304 | warn | at processTicksAndRejections (internal/process/task_queues.js:79:11)
spotify-premium.0 | 2020-05-12 21:41:12.304 | warn | at flush (/opt/iobroker/node_modules/asap/raw.js:50:29)
spotify-premium.0 | 2020-05-12 21:41:12.304 | warn | at /opt/iobroker/node_modules/promise/lib/core.js:123:15
spotify-premium.0 | 2020-05-12 21:41:12.304 | warn | at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12)
spotify-premium.0 | 2020-05-12 21:41:12.304 | warn | at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:318:38
spotify-premium.0 | 2020-05-12 21:41:12.304 | warn | (14936) Error
spotify-premium.0 | 2020-05-12 21:41:12.303 | warn | at processTicksAndRejections (internal/process/task_queues.js:79:11)
spotify-premium.0 | 2020-05-12 21:41:12.303 | warn | at flush (/opt/iobroker/node_modules/asap/raw.js:50:29)
spotify-premium.0 | 2020-05-12 21:41:12.303 | warn | at /opt/iobroker/node_modules/promise/lib/core.js:123:15
spotify-premium.0 | 2020-05-12 21:41:12.303 | warn | at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12)
spotify-premium.0 | 2020-05-12 21:41:12.303 | warn | at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:881:20
spotify-premium.0 | 2020-05-12 21:41:12.303 | warn | at getPlaylistTracks (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1019:12)
spotify-premium.0 | 2020-05-12 21:41:12.303 | warn | at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:206:21)
spotify-premium.0 | 2020-05-12 21:41:12.303 | warn | (14936) Error
spotify-premium.0 | 2020-05-12 21:41:12.303 | warn | (14936) http request error not handled, please debug
spotify-premium.0 | 2020-05-12 21:41:05.500 | warn | (14936) error on load tracks: 504
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at processTicksAndRejections (internal/process/task_queues.js:79:11)
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at flush (/opt/iobroker/node_modules/asap/raw.js:50:29)
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at /opt/iobroker/node_modules/promise/lib/core.js:123:15
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12)
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:318:38
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | (14936) Error
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at processTicksAndRejections (internal/process/task_queues.js:79:11)
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at flush (/opt/iobroker/node_modules/asap/raw.js:50:29)
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at /opt/iobroker/node_modules/promise/lib/core.js:123:15
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at tryCallOne (/opt/iobroker/node_modules/promise/lib/core.js:37:12)
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at /opt/iobroker/node_modules/iobroker.spotify-premium/main.js:881:20
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at getPlaylistTracks (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:1019:12)
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | at sendRequest (/opt/iobroker/node_modules/iobroker.spotify-premium/main.js:206:21)
spotify-premium.0 | 2020-05-12 21:41:05.499 | warn | (14936) Error
spotify-premium.0 | 2020-05-12 21:41:05.497 | warn | (14936) http request error not handled, please debug
spotify-premium.0 | 2020-05-12 21:40:17.328 | info | (14936) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.spotify-premium, node: v12.16.3, js-controller: 3.1.4
```

Node-Version:  v12.16.3
Nodejs-Version:  v12.16.3
NPM-Version:  6.14.4
js-controller:  3.1.4
Adapter:  Spotify-Premium  Version 1.1.0 

Discussion in ioBroker Forum: https://forum.iobroker.net/topic/33069/spotify-premium-adapter-viele-warnings-bei-adapterstart

**Comment by maxalw** [comment]
It can be quite challenging to choose the best antivirus app for your Android device when there are many options. That's why we did the job and tested many different antivirus software. Here's the article with a list of best antivirus apps for Android: https://celltrackingapps.com/free-android-antivirus/

**Comment by Apollon77** [comment]
Please retry ... 504 is normally a temporary server issue
